os:
  - osx
  - linux
language: node_js
node_js:
  - "node"
  - "--lts"
notifications:
  email: false
install:
  - npm install
script:
  - npm run lint
  - npm run test
after_script:
  - node ./node_modules/.bin/istanbul cover --include-all-sources command.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
