language: node_js
before_install:
  - npm install -g n
  - n $NODE_VERSION
env:
  - NODE_VERSION=latest
  - NODE_VERSION=stable
  - NODE_VERSION=lts
  - NODE_VERSION=0.12
sudo: false
install:
  - npm install -g
  - npm install
  - npm install istanbul coveralls codecov.io
script:
  - weather
  - weather --live
  - weather --help
  - weather -V
after_script:
  - node ./node_modules/.bin/istanbul cover --include-all-sources command.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js
