language: node_js
node_js:
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

install:
  - npm install -g
  - npm install istanbul coveralls codecov.io

script:
  - weather get
  - weather
after_script:
  - npm run cover
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js

matrix:
  allow_failures:
    - "4.0"
    - "0.12"
    - "0.11"
    - "0.10"
