language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

install:
  - npm install
  - npm install -g

script:
  - weather get
  - weather
after_script:
  - npm run test
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

matrix:
  allow_failures:
    - node_js: "0.12"
    - node_js: "0.11"
    - node_js: "0.10"
    - node_js: "iojs"
