language: node_js
node_js:
  - "stable"
  - "4"
  - "0.12"
install:
  - npm install -g
  - npm install istanbul coveralls codecov.io
script:
  - weather get
  - weather
after_script:
  - node ./node_modules/.bin/istanbul cover test/test_coverage.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js
matrix:
  allow_failures:
    - node_js: "stable"
    - node_js: "4"
    - node_js: "0.12"
cache:
  directories:
    - node_modules
