language: node_js
node_js:
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
install:
  - npm install -g
  - npm install istanbul coveralls codecov.io
script:
  - weather get
  - weather
after_script:
  - node ./node_modules/.bin/istanbul --include-all-sources cover test_coverage.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js
matrix:
  allow_failures:
    - node_js: "4"
    - node_js: "0.12"
    - node_js: "0.11"
    - node_js: "0.10"
