language: node_js
sudo: false
node_js:
  - "stable"
  - "4"
  - "0.12"
install:
  - npm install -g
  - npm install
  - npm update istanbul coveralls codecov.io
script:
  - weather
  - weather --live
  - weather --help
  - weather -V
after_script:
  - node ./node_modules/.bin/istanbul cover --include-all-sources command.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js
cache:
  directories:
    - node_modules
