language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

install:
  - npm install -g

script:
  - weather get
  - weather

matrix:
  include:
    - os: linux
      env: TARGET_ARCH=arm
    - os: linux
      env: TARGET_ARCH=ia32
  allow_failures:
    - env: TARGET_ARCH=arm
    - env: TARGET_ARCH=ia32
