name: CI
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm ci
      - run: npm run lint
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            **/node_modules
          key: '${{ runner.os }}-${{ hashFiles(''**/lockfiles'') }}'
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm ci
      - run: npm run build
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            **/node_modules
          key: '${{ runner.os }}-${{ hashFiles(''**/lockfiles'') }}'
  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.0.0
        with:
          github-token: '${{secrets.GITHUB_TOKEN}}'
